spring:
  profiles:
    active: dev
  data:
    web:
      pageable:
        max-page-size: 50
        default-page-size: 20
server:
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
logging:
  level:
    study: debug 
    org.hibernate.SQL: debug #logger를 통해 출력
    org.hibernate.type: trace #SQL 쿼리 파라미터를 확인할 수 있다
    org.spring.framework.web: debug 
    org.springframework.security: debug
    
---
spring:
  profiles:
  - dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true # System.out을 통해 출력
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
---
spring:
  profiles:
  - prod
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true # System.out을 통해 출력
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100